name: CI with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose

      - name: Start Services
        run: docker-compose up -d

      - name: Wait for Database
        run: |
          echo "Waiting for the database to be ready..."
          until docker exec durazzo_postgres_1 pg_isready -U postgres; do
            sleep 1
          done

      - name: Run Tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb?sslmode=disable
        run: make test

      - name: Run main
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb?sslmode=disable
        run: make run